- src/main/java/io/dinject/javalin/generator/TypeMap.java
I was using the library and had an issue with floats and I have tried to add them to the code
Please have a look,
Tijs
> Added asFloat and fixed a type LongHander --> LongHandler

- src/main/java/io/dinject/javalin/generator/MethodReader.java
- src/main/java/io/dinject/javalin/generator/Processor.java
- src/main/java/io/dinject/javalin/generator/openapi/DocContext.java
- src/main/java/io/dinject/javalin/generator/openapi/MethodDocBuilder.java
Hi Rob,
I wanted to use tags so I tried to add the functionality and you can now add a one or multiple tags to a controller or to the method itself. They will be added instead of overwritten if you add multiple.
Small example how to add them:
@Tag(name="ControllerTag")
@Controller
public class Controller {
@Tag(name = "EndpointTag")
@Get
public void get(Long id)  {}
@Tags({
@Tag(name="tag 1", description="Tag 1"),
@Tag(name="tag 2", description="Tag 2")
})
@Post
public void post() {}
}
I must admin not sure if this is the correct way to implement it but it seems to work :)
Tijs
> Added the @Tag and @Tags functionality.

- http-generator-core/src/main/java/io/avaje/http/generator/core/Constants.java
- http-generator-helidon/src/main/java/io/avaje/http/generator/helidon/ControllerWriter.java
- http-generator-javalin/src/main/java/io/avaje/http/generator/javalin/ControllerWriter.java
- http-generator-jex/src/main/java/io/avaje/http/generator/jex/ControllerWriter.java
- http-generator-spark/src/main/java/io/avaje/http/generator/spark/ControllerWriter.java
- pom.xml
- tests/test-client/pom.xml
- tests/test-helidon/pom.xml
- tests/test-helidon/src/test/java/org/example/BaseWebTest.java
- tests/test-javalin/pom.xml
- tests/test-javalin/src/test/java/org/example/myapp/BaseWebTest.java
- tests/test-javalin/src/test/java/org/example/myapp/HelloControllerTest.java
- tests/test-jex/pom.xml
- tests/test-spark/pom.xml
- Bumps to avaje-inject 6.x and $Factory
- Bumps avaje-http-hibernate-validator to 2.5
- Bumps http client used in tests
> Bump to avaje-inject 6.x with $Factory for request scoped controllers

- http-generator-core/src/main/java/io/avaje/http/generator/core/openapi/SchemaDocBuilder.java
Using  `types.getArrayType(type)` seems to convert an array TypeMirror object into a 2D array. e.g. `byte[]` -> `byte[][]`. So when the `getComponentType()` method is called the same base `byte[]` TypeMirror is returned, causing a loop. Fixes #89
Tested on this [Controller](https://github.com/SentryMan/Avaje-Javalin-API-Example/blob/df1359f7dee572e13bfe600c6e2d6756a400231e/src/main/java/com/jojo/javalin/api/controller/ControllerClass.java), which generates this [ControllerClass$Route.java](https://github.com/SentryMan/Avaje-Javalin-API-Example/blob/708f92abcf51ba63b2e46d31a5b8788bcb115b1d/ControllerClass%24Route.java) and [OpenAPI json](https://github.com/SentryMan/Avaje-Javalin-API-Example/blob/ed6fc66e41e201efb833176bee968776d459471c/openapi.json)
> Now get Component Type from Array TypeMirror

- http-generator-client/src/main/java/io/avaje/http/generator/client/ClientMethodWriter.java
> Add support for List/Array Types in client generation

- README.md
- http-generator-client/src/main/java/io/avaje/http/generator/client/ClientMethodWriter.java
- http-generator-client/src/main/java/io/avaje/http/generator/client/ClientProcessor.java
- http-generator-client/src/main/java/io/avaje/http/generator/client/ClientWriter.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/JsonBUtil.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/UType.java
- http-generator-helidon/src/main/java/io/avaje/http/generator/helidon/ControllerMethodWriter.java
- http-generator-javalin/src/main/java/io/avaje/http/generator/javalin/ControllerWriter.java
- http-generator-javalin/src/main/java/io/avaje/http/generator/javalin/JavalinProcessor.java
- http-generator-nima/src/main/java/io/avaje/http/generator/helidon/nima/ControllerWriter.java
- http-generator-nima/src/main/java/io/avaje/http/generator/helidon/nima/NimaProcessor.java
- tests/test-client/pom.xml
Now can do wacky stuff like this and have it work.
```
@Get("/get3")
Gen<RequestModel, String, Integer> getty3() {
return new Gen<>(new RequestModel("This Model class isn't named that well"), "stringy", 0);
}
@Json
public record Gen<T, T2, T3>(T o, @Ignore T2 ignored, T3 third) {}
```
- Adds JsonB types to imports and uses the short name in the generated source
- Enhance Client Processor to generate JsonB Parameterized types
- Enhances UType to be able to retrieve the full generic type of a param for certain Generic Classes
- Enhance JsonBUtil to write Parameterized Types for JsonB controllers
Has a dependency on this PR: https://github.com/avaje/avaje-jsonb/pull/47 
Has a dependency on this PR as well: https://github.com/avaje/avaje-http-client/pull/56
> Support generic jsonb types

- http-api/src/main/java/io/avaje/http/api/MatrixParam.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/ElementReader.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/PathSegments.java
- tests/test-javalin-jsonb/src/main/java/org/example/myapp/web/test/TestController.java
Now I've never used matrix params in my life. But if I did, I'd celebrate having goofy characters like hyphens.
- Creates new annotation
- Element reader detects this annotation and uses the value if available
- sanitizes generated path segment names
Solves #43
> Create @MatrixParam Annotation

- http-generator-core/pom.xml
- http-generator-core/src/main/java/io/avaje/http/generator/core/openapi/DocContext.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/openapi/JsonFormatter.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/openapi/OpenAPISerializer.java
- http-generator-core/src/main/java/module-info.java
So I was mildly inconvenienced when I was using this. It looks like when I try to use the AP with maven provided scope only in a project that doesn't use jackson at all. I get issues.
```
<dependency>
<groupId>io.avaje</groupId>
<artifactId>avaje-inject-generator</artifactId>
<version>${avaje.inject.version}</version>
<scope>provided</scope>
</dependency>
<dependency>
<groupId>io.avaje</groupId>
<artifactId>avaje-jsonb-generator</artifactId>
<version>${avaje.jsonb.version}</version>
</dependency>
<dependency>
<groupId>io.avaje</groupId>
<artifactId>avaje-http-javalin-generator</artifactId>
<version>${avaje.http.version}</version>
<scope>provided</scope>
</dependency>
```
I get this error.
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile …
```
> Remove Jackson/Custom Serialize OpenAPI json

- README.md
- http-api/src/main/java/io/avaje/http/api/Controller.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/ControllerReader.java
- tests/test-helidon/src/main/java/org/example/FooController.java
Now we can use one annotation to define a controller path instead of using Controller + Path
- Updates Controller annotation to support path
- Updates reader to get the path value from controller (Will prefer Controller annotation over Path annotation to get the path)
> Now can define path in @Controller

- http-generator-core/src/main/java/io/avaje/http/generator/core/Util.java
JsonB has beef with annotations I guess.
> Fix Annotations when using JsonB

- http-generator-core/src/main/java/io/avaje/http/generator/core/ControllerReader.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/ElementReader.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/MethodReader.java
Now we can do wacky stuff like this 
```
@Valid
@Post("/valid")
ResponseModel valid(@Valid RequestModel m) {
}
```
- now if validation annotation is on a body param will generate validation code
- sorta support jakarta annotations ( Now somebody could implement Validator with Jakarta if they want)
Partially takes care of #127
> Can validate request body

- http-client/src/main/java/io/avaje/http/client/BodyAdapter.java
- http-client/src/main/java/io/avaje/http/client/DHttpAsync.java
- http-client/src/main/java/io/avaje/http/client/DHttpClientContext.java
- http-client/src/main/java/io/avaje/http/client/DHttpClientRequest.java
- http-client/src/main/java/io/avaje/http/client/HttpAsyncResponse.java
- http-client/src/main/java/io/avaje/http/client/HttpClientResponse.java
- http-client/src/main/java/io/avaje/http/client/JsonbBodyAdapter.java
- http-client/src/test/java/io/avaje/http/client/HelloControllerTest.java
These allow access to the http status code and headers for success responses that we want as a bean, list of stream.
```java
final HttpResponse<MyDto> response = client.request()
.path("hello/saveform")
.formParam("name", "Bax")
.formParam("email", "Bax@foo.com")
.POST()
.as(MyDto.class);           <!-- HERE !!!
// access to status code and headers
int statusCode = response.statusCode();
HttpHeaders headers = response.headers();
// with body converted to the type we desire
MyDto body = response.body();
```
> [http-client] ENH: Add response as() methods that return HttpResponse wrapping bean, list and stream

- http-client/src/main/java/io/avaje/http/client/HttpApiProvider.java
- http-client/src/test/java/org/example/github/SimpleProvider.java
- http-client/src/test/java/org/example/github/httpclient/Simple$HttpClient.java
- http-generator-client/src/main/java/io/avaje/http/generator/client/ClientMethodWriter.java
- http-generator-client/src/main/java/io/avaje/http/generator/client/ClientWriter.java
- tests/test-client-generation/src/test/java/org/example/SimpleTest.java
- tests/test-client/src/main/java/example/github/SimpleHttpClient.java
This also changes the HttpApiProvider interface to use HttpClient so this generated code really wants the same version of the HttpClient which I think is reasonable.
> [http-client] Update the client generation to use HttpClient

- http-generator-core/src/main/java/io/avaje/http/generator/core/ProcessingContext.java
IntelliJ warned that for `javax && !jakarta` the !jakarta part was always true. That leads to this simplification.
> Simplify useJavax determination in ProcessingContext

- http-client/src/main/java/io/avaje/http/client/DHttpCall.java
- http-client/src/main/java/io/avaje/http/client/HttpCallResponse.java
- http-generator-client/src/main/java/io/avaje/http/generator/client/ClientMethodWriter.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/UType.java
- tests/test-client-generation/src/main/java/org/example/WithAsResponseApi.java
Supports code generation for client API methods like the following:
```java
@Client
public interface MyApi {
@Get("/as/{id}")
HttpResponse<Repo> getAs(UUID id);
@Get("/as-list/{id}")
HttpResponse<List<Repo>> getAsList(UUID id);
@Get("/as-stream/{id}")
HttpResponse<Stream<Repo>> getAsStream(UUID id);
@Get("/call-as/{id}")
HttpCall<HttpResponse<Repo>> getCallAs(UUID id);
@Get("/call-as-list/{id}")
HttpCall<HttpResponse<List<Repo>>> getCallAsList(UUID id);
@Get("/call-as-stream/{id}")
HttpCall<HttpResponse<Stream<Repo>>> getCallAsStream(UUID id);
}
```
> [http-client] Add code generation for the as() methods returning HttpResponse<E> etc

- http-hibernate-validator/pom.xml
- http-hibernate-validator/src/main/java/io/avaje/http/hibernate/validator/package-info.java
- http-hibernate-validator/src/main/java/module-info.java
Also remove @InjectModule as we just use it as a avaje-inject plugin (so it should not be both)
> Add module-info to Hibernate validator (Jakarta)

- http-api/src/main/java/io/avaje/http/api/OpenAPIResponse.java
- http-api/src/main/java/io/avaje/http/api/OpenAPIResponses.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/ControllerReader.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/MethodReader.java
- tests/test-javalin-jsonb/src/main/java/org/example/myapp/web/test/HealthController.java
- tests/test-javalin-jsonb/src/test/resources/expectedInheritedOpenApi.json
- change `@OpenAPIResponse` to work on classes
- if defined on a class all the routes in the class will  have the definition added to the openapi
- make interface-level roles inheritable.
Now instead of doing:
```
public class MyController {
@OpenAPIResponse(
responseCode = "403",
description = "Insufficient rights to this resource."
)
@Get("/some-authenticated-route")
public Object getObject(...) { ... }
@OpenAPIResponse(
responseCode = "403",
description = "Insufficient rights to this resource."
)
@Get("/another-authenticated-route")
public Object getObject2(...) { ... }
}
```
We can do this:
```
@OpenAPIResponse(
responseCode = "403",
description = "Insufficient rights to this resource."
)
public class MyController {
@Get("/some-authenticated-route")
public Object getObject(...) { ... …
```
> Inherit interface roles and class openAPIResponse

- http-generator-core/src/main/java/io/avaje/http/generator/core/JsonBUtil.java
- http-generator-javalin/src/main/java/io/avaje/http/generator/javalin/ControllerWriter.java
- tests/test-javalin-jsonb/src/main/java/org/example/myapp/web/test/TestController.java
Similar to https://github.com/avaje/avaje-http/pull/159 but with a slightly different approach. I decided after some more time with the code that it'd be best to update `jsonTypes` when it's being generated rather than having the dodgy if statements when we iterate through the `jsonTypes.values()`.
I do like the `UType.isCFuture()` definition though as it creates a better standardisation. 
Thoughts?
Fixes #158
> ISSUE-158: Fix CompletableFuture jsonb generation

- http-generator-core/src/main/java/io/avaje/http/generator/core/ElementReader.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/TypeMap.java
- tests/test-javalin-jsonb/src/main/java/org/example/myapp/web/test/ServerType.java
- tests/test-javalin-jsonb/src/main/java/org/example/myapp/web/test/TestController.java
- tests/test-javalin-jsonb/src/main/java/org/example/myapp/web/test/TestController2.java
Now can use simple Enums as Query Params
- adds an Enum TypeHandler for Certain Param Types
This PR is further expanded by #167
> Support Enum Query/Form Parameters

- http-api/src/main/java/io/avaje/http/api/RequestTimeout.java
- http-client/pom.xml
- http-generator-client/src/main/java/io/avaje/http/generator/client/ClientMethodWriter.java
- http-generator-client/src/main/java/io/avaje/http/generator/client/ClientProcessor.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/MethodReader.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/package-info.java
Now can override the global timeout on the generated client interfaces
> Add Request Timeout Annotation

- http-client/src/main/java/io/avaje/http/client/DHttpClientRequest.java
- http-client/src/main/java/io/avaje/http/client/HttpClientRequest.java
- http-client/src/main/java/io/avaje/http/client/UrlBuilder.java
- http-client/src/test/java/io/avaje/http/client/DHttpClientRequestTest.java
- http-client/src/test/java/io/avaje/http/client/HelloControllerTest.java
- tests/test-javalin-jsonb/src/test/java/org/example/myapp/HelloControllerTest.java
- tests/test-javalin/src/test/java/org/example/myapp/HelloControllerTest.java
- adds `header(String, Collection<String>)` and `queryparam(String, Collection<String>)`
- modifies uriBuilder to add multiple query parameters for collections
- modifies query param/header method to detect if the object is a collection
> HttpClientRequest Now Supports Multi-Value Headers/Query Parameters

- http-hibernate-validator/pom.xml
- http-hibernate-validator/src/main/java/io/avaje/http/hibernate/validator/ValidatorProvider.java
This will prevent the eventual `NoSuchMethod` error when used with inject 9.0.
> Update Validator Plugin (Jakarta)

- http-generator-core/src/main/java/io/avaje/http/generator/core/openapi/OpenAPISerializer.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/openapi/SchemaDocBuilder.java
- tests/test-javalin-jsonb/src/main/resources/public/openapi.json
- tests/test-jex/src/main/java/org/example/web/HelloDto.java
- tests/test-jex/src/main/resources/public/openapi.json
I tried to add support for enumeration types in the OpenAPI document, but the current JSON cannot handle it correctly. Whether to consider introducing swagger core to support document processing? I feel this is necessary.
> OpenAPI documents support enumeration types

- http-generator-core/src/main/java/io/avaje/http/generator/core/ElementReader.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/MethodParam.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/openapi/DocContext.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/openapi/SchemaDocBuilder.java
- tests/test-javalin-jsonb/src/main/java/org/example/myapp/web/GetBeanForm.java
- tests/test-javalin-jsonb/src/main/resources/public/openapi.json
Now bean param fields are correctly written to openapi.json
fixes #178
> BeanParam OpenAPI

- http-client/pom.xml
- http-client/src/main/java/io/avaje/http/client/DHttpClientContext.java
- http-client/src/main/java/io/avaje/http/client/DHttpClientRequest.java
- http-client/src/main/java/io/avaje/http/client/HttpClientRequest.java
- http-generator-client/src/main/java/io/avaje/http/generator/client/ClientMethodWriter.java
- http-generator-core/pom.xml
The use of `.getClass()` means that jsonb subtypes cannot work.
```
@Client
public interface Client {
@Post("/resource")
public Response createResource(ExtendableObject object);
}
```
Providing an `ExtendingObject` that extends ExtendableObject means that the JsonAdapter for ExtendableObject is not used, so the `@type` field is lost. This PR fixes that.
- Adds new `body` methods to HttpClientRequest to take the type parameter
- now generated clients will provide the type parameters
> (Http-Client) Support Jsonb SubTypes in request body

- http-client/src/main/java/io/avaje/http/client/BodyAdapter.java
- http-client/src/main/java/io/avaje/http/client/DHttpClientContext.java
- http-client/src/main/java/io/avaje/http/client/DHttpClientRequest.java
- http-client/src/main/java/io/avaje/http/client/HttpClientRequest.java
- http-client/src/main/java/io/avaje/http/client/JsonbBodyAdapter.java
- http-generator-client/src/main/java/io/avaje/http/generator/client/ClientMethodWriter.java
- tests/test-javalin-jsonb/src/main/java/org/example/myapp/web/ServerType.java
- tests/test-javalin-jsonb/src/main/java/org/example/myapp/web/test/TestController2.java
- adds method to use ParameterizedType
- use writeGeneric for body
> (Client) Support Generic Body Type

- http-generator-core/pom.xml
- http-generator-core/src/main/java/io/avaje/http/generator/core/ProcessingContext.java
> ThreadLocal Context

- http-generator-core/pom.xml
- http-generator-core/src/main/java/io/avaje/http/generator/core/ElementReader.java
- tests/test-javalin-jsonb/src/main/java/org/example/myapp/web/test/TestController.java
- tests/test-javalin-jsonb/src/main/java/org/example/myapp/web/test/TestController2.java
It seems the imports were not coming through for collections/bean param collections
> Fix Query Param Collection Imports

- http-client/src/main/java/io/avaje/http/client/BodyAdapter.java
- http-client/src/main/java/io/avaje/http/client/DHttpClientContext.java
- http-client/src/main/java/io/avaje/http/client/DHttpClientRequest.java
- http-client/src/main/java/io/avaje/http/client/HttpClientRequest.java
- http-client/src/main/java/io/avaje/http/client/HttpClientResponse.java
- http-client/src/main/java/io/avaje/http/client/HttpException.java
- http-client/src/main/java/io/avaje/http/client/JsonbBodyAdapter.java
Hmm, I'm thinking it would be good if we loosen the restriction from only parameterized types.
> [http client] Use more generic Type rather than ParameterizedType

- http-client/src/main/java/io/avaje/http/client/DHttpAsync.java
- http-client/src/main/java/io/avaje/http/client/DHttpCall.java
- http-client/src/main/java/io/avaje/http/client/HttpAsyncResponse.java
- http-client/src/main/java/io/avaje/http/client/HttpCallResponse.java
- http-client/src/main/java/io/avaje/http/client/HttpClientRequest.java
- http-client/src/main/java/io/avaje/http/client/HttpClientResponse.java
Updates JavaDoc and updates the Async Interfaces to use Type
> [http client] Change Async API to use more generic Type instead of ParameterizedType 

- http-api/src/main/java/io/avaje/http/api/Ignore.java
- http-api/src/main/java/io/avaje/http/api/IgnoreBeanField.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/BeanParamReader.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/package-info.java
- tests/test-javalin-jsonb/src/main/java/org/example/myapp/web/GetBeanForm.java
Also adds an @Ignore annotation for bean parameters. (have a case where I use the bean param object constructors to initialize other useful fields that are not expected parameters).
It's like a `Jsonb.Ignore(serialization=true)` but for http.
> Add @Ignore for ignoring a BeanParam field (or query param field)

- http-api/src/main/java/io/avaje/http/api/context/ServerContext.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/BeanParamReader.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/ElementReader.java
also fix that server context methods aren't public
fixes #207 and #208
> Fix BeanParam imports

- http-api/src/main/java/io/avaje/http/api/Controller.java
- http-api/src/main/java/io/avaje/http/api/Delete.java
- http-api/src/main/java/io/avaje/http/api/Get.java
- http-api/src/main/java/io/avaje/http/api/InstrumentServerContext.java
- http-api/src/main/java/io/avaje/http/api/Patch.java
- http-api/src/main/java/io/avaje/http/api/Post.java
- http-api/src/main/java/io/avaje/http/api/Put.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/ControllerReader.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/MethodReader.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/package-info.java
- tests/test-javalin-jsonb/src/main/resources/public/openapi.json
- tests/test-nima-jsonb/src/main/java/org/example/TestController.java
I honestly don't know what possessed me to make the initial design not use a dedicated annotation.
> InstrumentServerContext annotation

- http-generator-javalin/src/main/java/io/avaje/http/generator/javalin/ControllerMethodWriter.java
Now when using ServerContext, we can write to the context response from an aspect and the controller method's result serialization can be skipped.
Fixes https://github.com/avaje/avaje-http/issues/210 from a certain point of view.
> Don't serialize twice when Javalin Context is already committed

- http-api/src/main/java/io/avaje/http/api/InstrumentServerContext.java
- http-api/src/main/java/io/avaje/http/api/spi/MetaData.java
- http-api/src/main/java/module-info.java
- http-client/src/main/java/io/avaje/http/client/DHttpApi.java
- http-client/src/main/java/io/avaje/http/client/DHttpClientContext.java
- http-client/src/main/java/io/avaje/http/client/HttpApiProvider.java
- http-client/src/main/java/io/avaje/http/client/HttpClient.java
- http-client/src/main/java/module-info.java
- http-generator-client/pom.xml
- http-generator-client/src/main/java/io/avaje/http/generator/client/ClientProcessor.java
- http-generator-client/src/main/java/io/avaje/http/generator/client/ClientWriter.java
- http-generator-client/src/main/java/io/avaje/http/generator/client/ComponentMetaData.java
- http-generator-client/src/main/java/io/avaje/http/generator/client/ComponentReader.java
- http-generator-client/src/main/java/io/avaje/http/generator/client/SimpleComponentWriter.java
- http-generator-client/src/main/java/io/avaje/http/generator/client/TopPackage.java
- http-generator-client/src/main/java/module-info.java
- http-generator-client/src/test/java/io/avaje/http/generator/client/ClientProcessorTest.java
- http-generator-client/src/test/java/io/avaje/http/generator/client/clients/ApiClient.java
- http-generator-core/pom.xml
- http-generator-core/src/main/java/io/avaje/http/generator/core/Constants.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/ProcessingContext.java
- pom.xml
- tests/test-client/src/test/java/example/github/GithubTest.java
- Make `HttpApiProvider` a functional interface
- now generates a `GeneratedComponent` class that adds `HttpApiProvider`s to ```DHttpApi```
- no longer generates a provider nested class. (the generated client constructor is used as an HttpApiProvider)
- client processor test for easier debugging of issues 
- can reflectively retrieve implementations using `HttpClient` as well as `HttpClientContext`. 
fixes #217 
this is how the generated component looks
```java
@Generated("avaje-client-generator")
public class GeneratedHttpComponent implements HttpClient.GeneratedComponent {
@Override
public void register(Map<Class<?>, HttpApiProvider<?>> providerMap) {
providerMap.put(ApiClient.class, ApiClientHttpClient::new);
}
}
```
> Change how Generated Clients are registered.

- http-client-gson-adapter/src/main/java/io/avaje/http/client/gson/GsonBodyAdapter.java
- http-client/src/main/java/io/avaje/http/client/HttpAsyncResponse.java
- http-client/src/main/java/io/avaje/http/client/HttpCallResponse.java
- http-client/src/main/java/io/avaje/http/client/HttpClient.java
- http-client/src/main/java/io/avaje/http/client/HttpClientResponse.java
Migrate from withHandler(HttpResponse.BodyHandler<E> bodyHandler) to handler(HttpResponse.BodyHandler<E> bodyHandler)
> [HttpClient] Remove deprecated method withHandler() migrate to handler()

- .lift.toml
- http-api/src/main/java/io/avaje/http/api/Client.java
- http-generator-client/src/main/java/io/avaje/http/generator/client/ClientProcessor.java
- http-generator-client/src/test/java/io/avaje/http/generator/client/clients/ExampleClient.java
- http-generator-client/src/test/java/io/avaje/http/generator/client/clients/ExampleClient2.java
- http-generator-client/src/test/java/io/avaje/http/generator/client/clients/UserClient.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/ControllerReader.java
Now will generate the extended interface's http method implementation.
- adds a parameter to `@Client` that will disable generation is desired
- modify generation to read super client interface methods
> Extendable Clients

- http-generator-core/src/main/java/io/avaje/http/generator/core/BaseProcessor.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/ProcessingContext.java
- http-generator-javalin/src/main/java/io/avaje/http/generator/javalin/ControllerMethodWriter.java
- http-generator-nima/src/main/java/io/avaje/http/generator/helidon/nima/ControllerMethodWriter.java
Fixes wrong headers being added when body content exceeds a certain size. Also adds a flag to disable Jsonb direct writes.
> (Javalin Jsonb) Add support for disableDirectWrites to NOT write directly to Jetty HttpOutput Stream

- README.md
- http-generator-client/src/main/java/io/avaje/http/generator/client/ClientProcessor.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/BaseProcessor.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/JsonBUtil.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/ProcessingContext.java
- http-generator-javalin/src/main/java/io/avaje/http/generator/javalin/JavalinProcessor.java
- http-generator-nima/src/main/java/io/avaje/http/generator/helidon/nima/NimaProcessor.java
- tests/test-javalin-jsonb/src/test/java/io/avaje/http/generator/JavalinProcessorTest.java
- tests/test-nima-jsonb/src/test/java/io/avaje/http/generator/NimaProcessorTest.java
When you add the generators as a provided dependency on a modular project, the use of `Class.forName` to detect classes doesn't fly.
> Fix Jsonb Controller for modular projects without compiler plugin

- http-generator-core/src/main/java/io/avaje/http/generator/core/Util.java
Now can handle all the wacky annotation situations
> Update Trim Annotation Logic

- http-api/src/main/java/io/avaje/http/api/Valid.java
- http-api/src/main/java/io/avaje/http/api/Validator.java
- http-client/src/test/java/org/example/webserver/HelloController$Route.java
- http-generator-client/src/main/java/io/avaje/http/generator/client/ClientPlatformAdapter.java
- http-generator-core/pom.xml
- http-generator-core/src/main/java/io/avaje/http/generator/core/Constants.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/ControllerReader.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/ElementReader.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/MethodReader.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/PlatformAdapter.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/ValidPrism.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/package-info.java
- http-generator-helidon/src/main/java/io/avaje/http/generator/helidon/HelidonPlatformAdapter.java
- http-generator-javalin/src/main/java/io/avaje/http/generator/javalin/JavalinAdapter.java
- http-generator-jex/src/main/java/io/avaje/http/generator/jex/JexAdapter.java
- http-generator-nima/src/main/java/io/avaje/http/generator/helidon/nima/ControllerWriter.java
- http-generator-nima/src/main/java/io/avaje/http/generator/helidon/nima/NimaPlatformAdapter.java
- http-hibernate-validator/pom.xml
- http-hibernate-validator/src/main/java/io/avaje/http/hibernate/validator/BeanValidator.java
- tests/test-javalin-jsonb/pom.xml
- tests/test-javalin-jsonb/src/main/java/org/example/myapp/web/GetBeanForm.java
- tests/test-javalin-jsonb/src/main/java/org/example/myapp/web/HelloForm.java
- tests/test-javalin/pom.xml
- tests/test-javalin/src/main/java/org/example/myapp/web/GetBeanForm.java
- tests/test-javalin/src/main/java/org/example/myapp/web/HelloController.java
- tests/test-javalin/src/main/java/org/example/myapp/web/HelloForm.java
- tests/test-jex/pom.xml
- tests/test-jex/src/main/java/org/example/web/HelloController.java
- tests/test-jex/src/main/java/org/example/web/HelloDto.java
In preparation for Avaje Validation:
- Modifies Validator interface to accept language headers and adds a method to resolve locales
- Modify Hibernate Validator to match
- Modify Generation to extract language header and groups for validation
> Add Accept Language header to validation

- README.md
> Add Client to README

- .github/workflows/build.yml
- http-api/src/main/java/io/avaje/http/api/ValidationException.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/ElementReader.java
also have a separate line for validation accept header.
> Add ValidationException Cause

- http-api/src/main/java/io/avaje/http/api/ValidationException.java
- http-client/pom.xml
- http-client/src/test/java/io/avaje/http/client/HelloControllerTest.java
- http-client/src/test/java/org/example/github/RepoJsonAdapter.java
- http-client/src/test/java/org/example/webserver/ErrorResponse.java
- http-hibernate-validator/pom.xml
- http-hibernate-validator/src/main/java/io/avaje/http/hibernate/validator/BeanValidator.java
- tests/test-javalin-jsonb/pom.xml
- tests/test-javalin-jsonb/src/test/java/org/example/myapp/ErrorResponse.java
- tests/test-javalin-jsonb/src/test/java/org/example/myapp/HelloControllerTest.java
- tests/test-javalin/pom.xml
- tests/test-javalin/src/test/java/org/example/myapp/ErrorResponse.java
- tests/test-javalin/src/test/java/org/example/myapp/HelloControllerTest.java
- tests/test-jex/pom.xml
- tests/test-jex/src/test/java/org/example/web/ErrorResponse.java
- tests/test-jex/src/test/java/org/example/web/HelloControllerTest.java
This is effectively an API breaking change from Map -> List + explicit type
The ValidationException.Error type is fairly opinionated. If that doesn't match application requirements the error handler needs to obtain the cause and pull the constraint violation errors from that to build its error response payload message
> Change ValidationException errors to be a List<ValidationException.Error>

- http-api/src/main/java/io/avaje/http/api/Produces.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/MethodReader.java
- tests/test-javalin-jsonb/src/main/java/org/example/myapp/web/test/OpenAPIController.java
- tests/test-nima-jsonb/src/main/java/org/example/TestController.java
- tests/test-nima-jsonb/src/test/java/org/example/TestControllerTest.java
In line with ExceptionHandler and more obvious as to what it does
> Rename Produces defaultStatus -> statusCode

- http-generator-core/src/main/java/io/avaje/http/generator/core/MethodReader.java
- http-generator-helidon/src/main/java/io/avaje/http/generator/helidon/nima/ControllerMethodWriter.java
- http-generator-javalin/src/main/java/io/avaje/http/generator/javalin/ControllerMethodWriter.java
- http-generator-jex/src/main/java/io/avaje/http/generator/jex/ControllerMethodWriter.java
- tests/test-javalin-jsonb/src/main/java/org/example/myapp/web/HelloController.java
- tests/test-javalin-jsonb/src/main/resources/public/openapi.json
- tests/test-javalin-jsonb/src/test/java/org/example/myapp/HelloControllerTest.java
- tests/test-nima-jsonb/src/main/java/org/example/TestController.java
- tests/test-nima-jsonb/src/test/java/org/example/TestControllerTest.java
Support use case that requires programmatic control of status code but non-void controller method. This might be marginal but I don't think its a negative.
> Only generated response status code when statusCode > 0

- http-generator-client/src/main/java/io/avaje/http/generator/client/ClientMethodWriter.java
- http-generator-client/src/test/java/io/avaje/http/generator/client/clients/UserClient.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/MethodParam.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/Util.java
- http-generator-javalin/src/main/java/io/avaje/http/generator/javalin/ControllerMethodWriter.java
Adds a way to detect if an element is a varArg, and generates the implementation with a vararg param instead of an array.
> [http-client] Generate VarArgs Correctly

- http-generator-helidon/src/main/java/io/avaje/http/generator/helidon/nima/ControllerMethodWriter.java
- http-generator-helidon/src/main/java/io/avaje/http/generator/helidon/nima/ControllerWriter.java
- tests/test-nima-jsonb/src/main/java/org/example/ErrorController.java
This makes it the generated code look like:
`res.status(OK_200);`
Rather than:
`res.status(200);`
> Nima - use Nima's Http.Status enum when the status code is known

- http-api/src/main/java/io/avaje/http/api/ValidationException.java
- http-client/src/test/java/io/avaje/http/client/HelloControllerTest.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/BaseProcessor.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/ElementReader.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/ProcessingContext.java
- http-generator-helidon/src/main/java/io/avaje/http/generator/helidon/nima/NimaPlatformAdapter.java
- http-generator-helidon/src/main/java/io/avaje/http/generator/helidon/nima/NimaProcessor.java
- http-generator-javalin/src/main/java/io/avaje/http/generator/javalin/JavalinAdapter.java
- http-generator-javalin/src/main/java/io/avaje/http/generator/javalin/JavalinProcessor.java
- tests/test-javalin-jsonb/src/main/java/org/example/myapp/web/test/TestController2.java
- tests/test-nima-jsonb/src/main/java/org/example/TestController.java
There's no reason I can see to have the exception be mutable.
Also form parameters can be multi-valued
> Make `ValidationException` Immutable/Support Multi-Value Form Parameters.

- http-api/src/main/java/io/avaje/http/api/javalin/After.java
- http-api/src/main/java/io/avaje/http/api/javalin/Before.java
- http-api/src/main/java/module-info.java
- http-generator-javalin/pom.xml
- http-generator-javalin/src/main/java/io/avaje/http/generator/javalin/JavalinProcessor.java
- http-generator-javalin/src/main/java/module-info.java
- tests/test-javalin-jsonb/src/main/java/org/example/myapp/web/test/TestController2.java
As I discovered earlier, it seems annotations and their processors can't be in the same module if you want it to work on the module-path automatically.
> Move javalin annotations out of Generator

- http-client/src/main/java/io/avaje/http/client/HttpException.java
- http-client/src/test/java/io/avaje/http/client/HelloControllerTest.java
If the response is read multiple times (say as String + decoded to a bean) then only read the response body once
> [http client] HttpException internally read the response body once

- http-client/src/main/java/io/avaje/http/client/DHttpClientContext.java
- http-client/src/main/java/io/avaje/http/client/HttpException.java
- http-client/src/test/java/io/avaje/http/client/HelloControllerTest.java
- http-generator-client/src/test/java/io/avaje/http/generator/client/clients/MappedException.java
Helper methods to make it easier for use cases that need logic in reading the HttpException that could be text or json etc
> [http client] HttpException add isPlainText() and contentType()

- http-api/src/main/java/io/avaje/http/api/OpenAPIResponse.java
- http-client/src/main/java/io/avaje/http/client/HttpClient.java
- http-client/src/main/java/io/avaje/http/client/HttpClientRequest.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/openapi/MethodDocBuilder.java
- tests/test-javalin-jsonb/src/main/java/org/example/myapp/web/test/HealthController.java
- tests/test-javalin-jsonb/src/main/java/org/example/myapp/web/test/OpenAPIController.java
> OpenAPIResponse int responseCode

- .github/workflows/build.yml
- README.md
- http-generator-helidon/pom.xml
- http-generator-helidon/src/main/java/io/avaje/http/generator/helidon/nima/ControllerMethodWriter.java
- http-generator-helidon/src/main/java/io/avaje/http/generator/helidon/nima/ControllerWriter.java
- http-generator-helidon/src/main/java/io/avaje/http/generator/helidon/nima/HelidonProcessor.java
- http-generator-helidon/src/main/java/io/avaje/http/generator/helidon/nima/NimaPlatformAdapter.java
- http-generator-helidon/src/main/java/module-info.java
- tests/pom.xml
- tests/test-nima-jsonb/pom.xml
- tests/test-nima-jsonb/src/main/java/org/example/ErrorController.java
- tests/test-nima-jsonb/src/main/java/org/example/HelloController.java
- tests/test-nima-jsonb/src/main/java/org/example/Main.java
- tests/test-nima-jsonb/src/main/java/org/example/TestController.java
- tests/test-nima-jsonb/src/test/java/io/avaje/http/generator/NimaProcessorTest.java
- tests/test-nima-jsonb/src/test/java/org/example/TestPair.java
- tests/test-nima/pom.xml
- tests/test-nima/src/main/java/org/example/Main.java
fixes #268 
relies on https://github.com/avaje/avaje-jsonb/pull/155
> Helidon 4.0-M2

- http-generator-client/src/main/java/io/avaje/http/generator/client/ClientMethodWriter.java
before:
```
// GET /mapped
@Override
public String mapped(String accept) {
.header("Accept", accept)
.path("mapped")
.errorMapper(io.avaje.http.generator.client.clients.MappedException::new)
.GET()
.asPlainString().body();
}
```
after:
```
// GET /mapped
@Override
public String mapped(String accept) {
.header("Accept", accept)
.path("mapped")
.errorMapper(MappedException::new)
.GET()
.asPlainString().body();
}
```
> [http-client] Use Short Type for method exception type

- http-client/src/main/java/io/avaje/http/client/DBaseBuilder.java
That is, do not store/keep the underlying HttpClient if it is being created as part of build().
This means that the build() method can be called
multiple times to create multiple clients with
different underlying HttpClient instances.
> [http client] When building default underlying HttpClient create each time

- http-generator-client/src/main/java/io/avaje/http/generator/client/ClientMethodWriter.java
- http-generator-client/src/main/java/io/avaje/http/generator/client/ClientPlatformAdapter.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/ElementReader.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/MethodParam.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/MethodReader.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/PlatformAdapter.java
- http-generator-helidon/src/main/java/io/avaje/http/generator/helidon/nima/NimaPlatformAdapter.java
- http-generator-javalin/src/main/java/io/avaje/http/generator/javalin/JavalinAdapter.java
- tests/test-client-generation/pom.xml
- tests/test-client-generation/src/main/java/org/example/CommonApi.java
- tests/test-client-generation/src/main/java/org/example/client/package-info.java
- tests/test-client-generation/src/test/java/org/example/CommonApiTest.java
When the interface has been previously compiled then the method arg names are effectively lost - become arg0, arg1, arg2 etc. In this case the generation can get the implied arg names for path parameters from the segments but for @QueryParam and @Header parameters we now need explicitly named arguments.
This change handles the path segments and gives a reasonable error for QueryParams and Headers etc that are not explicitly named.
> [http client] Generation for @Client.Import when argument names lost

- http-generator-client/src/main/java/io/avaje/http/generator/client/ClientMethodWriter.java
I find people don't tend to read error messages directly written on the generated source code.
> Use `logError` for the client import error message.

- .github/dependabot.yml
- .github/workflows/dependabot-merge.yml
- README.md
- http-generator-jex/pom.xml
- http-generator-jex/src/main/java/io/avaje/http/generator/jex/JexProcessor.java
- http-generator-jex/src/main/java/module-info.java
- http-generator-jex/src/main/resources/META-INF/services/javax.annotation.processing.Processor
- pom.xml
They disabled annotation processors by default in JDK 22
> Enable annotation processors in JDK 22

- README.md
- http-generator-client/src/main/java/io/avaje/http/generator/client/ClientMethodWriter.java
- http-generator-client/src/test/java/io/avaje/http/generator/client/clients/UserClient.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/PathSegments.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/Util.java
Now can dynamically determine the paths at runtime using system properties or avaje config.
With this, we can perform tomfoolery such as:
```java
@Client
public interface TitanFall {
@Get("/${titan}/${drop.point}")
Titan titanfall();
}
```
and the following will generate 
```java
@Generated("avaje-http-client-generator")
public class TitanFallHttpClient implements TitanFall {
private final HttpClient client;
public TitanFallHttpClient(HttpClient client) {
this.client = client;
}
//if available will use Config.get instead 
private static final String DROP_POINT = System.getProperty("drop.point");
private static final String TITAN = System.getProperty("titan");
// GET /${titan}/${drop.point}
@Override
public Titan titanfall() {
.path(TITAN).path(DROP_POINT)
.GET() …
```
> [http-client] Allow paths to be loaded from System Properties/Avaje Config

- http-client/src/main/java/io/avaje/http/client/DUrlBuilder.java
- http-generator-client/src/main/java/io/avaje/http/generator/client/ClientMethodWriter.java
- http-generator-client/src/test/java/io/avaje/http/generator/client/clients/Titan.java
- http-generator-client/src/test/java/io/avaje/http/generator/client/clients/TitanFall.java
now if we do something like:
```
@Override
public Titan titanfall() {
.path("https://something.com").path(DROP_POINT)
.GET()
.bean(Titan.class);
}
```
the base URL  will be switched to `https://something.com`.
- `path`  will reset the URL buffer if an HTTP scheme is detected in the given string
> [http-client] Reset base if an http scheme is detected

- http-generator-client/src/main/java/io/avaje/http/generator/client/AnnotationUtil.java
- http-generator-client/src/main/java/io/avaje/http/generator/client/ClientMethodWriter.java
- Now will only write the extra spaces for anotations when generating methods
- move property constants below the URI comments
> [http-client] Generated Client Formatting

- http-generator-core/src/main/java/io/avaje/http/generator/core/openapi/SchemaDocBuilder.java
Currently, only `NotNull` is supported
> [http-generator-core] OpenAPI Schema nullable property - Added support for NotEmpty and NotBlank 

- http-generator-core/src/main/java/io/avaje/http/generator/core/openapi/SchemaDocBuilder.java
This is to add support for `required` label on fields that are not nullable (any of "NotNull", "NotEmpty", "NotBlank") 
```json
"components": {
"schemas": {
"Provider": {
"required": [
"firstName",
"lastName"
],
"type": "object",
"properties": {
"firstName": {
"type": "string",
"nullable": false
},
"middleName": {
"type": "string"
},
"lastName": {
"type": "string",
"nullable": false
}
}
}
}
}
```
Sample redoc
> [http-generator-core] added required props

- http-generator-client/src/main/java/io/avaje/http/generator/client/ClientMethodWriter.java
- http-generator-client/src/main/java/io/avaje/http/generator/client/ClientWriter.java
- http-generator-client/src/test/java/io/avaje/http/generator/client/clients/TitanFall.java
now stuff like this works:
```java
public interface TitanFall {
@Get("/${titan}/${drop.point}")
Titan titanFall();
@Get("/${titan}/copium")
Titan titanFall3();
}
```
> [http-client] Prevent Duplicate Constants

- http-api-javalin/src/main/java/io/avaje/http/api/javalin/AfterMatched.java
- http-api-javalin/src/main/java/io/avaje/http/api/javalin/BeforeMatched.java
- http-api/pom.xml
- http-api/src/main/java/io/avaje/http/api/AvajeJavalinPlugin.java
- http-api/src/main/java/io/avaje/http/api/Validator.java
- http-api/src/main/java/module-info.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/ElementReader.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/ProcessingContext.java
- http-generator-javalin/src/main/java/io/avaje/http/generator/javalin/AbstractCustomMethodPrism.java
- http-generator-javalin/src/main/java/io/avaje/http/generator/javalin/ControllerMethodWriter.java
- http-generator-javalin/src/main/java/io/avaje/http/generator/javalin/ControllerWriter.java
- http-generator-javalin/src/main/java/io/avaje/http/generator/javalin/JavalinAdapter.java
- http-generator-javalin/src/main/java/io/avaje/http/generator/javalin/JavalinProcessor.java
- http-generator-javalin/src/main/java/io/avaje/http/generator/javalin/JavalinWebMethod.java
- tests/test-javalin-jsonb/pom.xml
- tests/test-javalin-jsonb/src/main/java/org/example/myapp/Main.java
- tests/test-javalin/pom.xml
- tests/test-javalin/src/main/java/org/example/myapp/Main.java
- tests/test-nima-jsonb/src/main/java/org/example/TestController.java
- tests/test-nima-jsonb/src/test/java/org/example/MyForm2.java
- tests/test-nima-jsonb/src/test/java/org/example/TestControllerTest.java
- tests/test-nima-jsonb/src/test/java/org/example/TestPair.java
- Adds new Before/After Matched handlers
- Adds a class for easy wiring the Javalin Plugins (they changed to a generic abstract class)
- Fix Validation Groups
Fixes #340
> Javalin 6-beta Support

- http-generator-core/src/main/java/io/avaje/http/generator/core/ProcessingContext.java
`io.javalin.config.JavalinConfig` is in both 5 and 6, which causes controllers to only generate with Javalin 6.
- now uses `io.javalin.config.RouterConfig` to determine if on Javalin 6
> Fix Javalin 5 generation not triggering properly

- http-client/src/main/java/module-info.java
To call things via ssl this is required, and yet I often forget to add it when creating jlink images
> [http client] Add `jdk.crypto.ec` to http client module

- http-client/src/main/java/module-info.java
It's deprecated now I guess: https://bugs.openjdk.org/browse/JDK-8312267
> Remove `jdk.crypto.ec`

- http-generator-core/src/main/java/io/avaje/http/generator/core/UType.java
- tests/test-nima-jsonb/src/main/java/org/example/path/PathTestController.java
- tests/test-nima-jsonb/src/main/java/org/example/path/nest/PathNestController.java
Fixes a bug where nested types in different packages don't generate imports correctly
> [helidon-generator] Fix Nested Types in other packages

- http-api/src/main/java/io/avaje/http/api/Headers.java
- http-generator-client/src/main/java/io/avaje/http/generator/client/ClientMethodWriter.java
- http-generator-client/src/main/java/io/avaje/http/generator/client/ClientProcessor.java
- http-generator-client/src/test/java/io/avaje/http/generator/client/clients/TitanFall.java
Adds something like Retrofits `@Headers` (I got sick of making default methods to add preset headers)
Now we can do stuff like this:
```java
@Client
@Headers("Content-Type: applicaton/json")
public interface TitanFall {
@Get("/${titan}/${drop.point}")
@Headers("Something: \\invalid\n\t")
Titan titanFall();
@Get("/${titan}/copium")
@Headers("      Accept    :   applicaton/json")
Titan titanFall3();
}
```
and the generated class will have
```java
// GET /${titan}/${drop.point}
private static final String DROP_POINT = System.getProperty("drop.point");
private static final String TITAN = System.getProperty("titan");
@Override
public Titan titanFall() {
.header("Something", "\\invalid")
.header("Content-Type", "applicaton/json")
.path(TITAN).path(DROP_POINT)
.GET() …
```
> [http-client] Add `@Headers` Annotation

- http-generator-core/src/main/java/io/avaje/http/generator/core/openapi/SchemaDocBuilder.java
- tests/test-nima-jsonb/src/main/java/org/example/Person.java
Modifies the schema builder to retrieve the record javadocs and associate the `@param`s with a record component
> Can now read record Javadocs for OpenApi

- http-generator-core/src/main/java/io/avaje/http/generator/core/ProcessingContext.java
disables module validation if the plugin is detected
> Support the Avaje Build Plugin

- http-client/src/main/java/io/avaje/http/client/BodyAdapter.java
- http-client/src/main/java/io/avaje/http/client/BodyContent.java
- http-client/src/main/java/io/avaje/http/client/DBodyContent.java
- http-client/src/main/java/io/avaje/http/client/DBodyContentS.java
- http-client/src/main/java/io/avaje/http/client/DHttpClientContext.java
- tests/test-nima-jsonb/src/main/java/org/example/TestController.java
- tests/test-nima-jsonb/src/test/java/io/avaje/http/generator/NimaProcessorTest.java
- tests/test-nima-jsonb/src/test/java/org/example/TestControllerTest.java
> httpclient: #426 Fix support for 204 no response body for HttpClient reading content

- http-generator-client/src/main/java/io/avaje/http/generator/client/ClientProcessor.java
- http-generator-client/src/main/java/io/avaje/http/generator/client/ClientSuffix.java
- http-generator-client/src/main/java/io/avaje/http/generator/client/ClientWriter.java
- http-generator-client/src/main/java/io/avaje/http/generator/client/ComponentMetaData.java
- http-generator-client/src/main/java/io/avaje/http/generator/client/SimpleComponentWriter.java
- http-generator-client/src/test/java/io/avaje/http/generator/client/ClientSuffixTest.java
- tests/test-client-generation/src/main/java/org/example/MyOtherHttpClient.java
- tests/test-client-generation/src/main/java/org/example/MySillyClient.java
Avoid duplicating HttpClient or Client in the generated client class name. If the client interface ends in "Client" then use the suffix of "Impl" otherwise use "HttpClient".
> [HttpClient] Generated client to use suffix of Impl or HttpClient

- http-generator-client/src/main/java/io/avaje/http/generator/client/ClientProcessor.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/BaseProcessor.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/ProcessingContext.java
- pom.xml
- will write services to `META-INF/generated services` if avaje spi is detected (I haven't added it as a transitive dependency because of potential shading shenanigans)
- uses avaje prisms to read and validate module-infos
- will run module validations on all processors
> Use avaje spi for service validation when available

- .github/dependabot.yml
Now dependabot should create a single PR for all the dependencies. [Example PR](https://github.com/SentryMan/avaje-javalin-api-example/pull/50)
> Update Dependabot Grouping

- http-generator-helidon/src/main/java/io/avaje/http/generator/helidon/nima/ControllerWriter.java
- http-generator-helidon/src/main/java/io/avaje/http/generator/helidon/nima/NimaPlatformAdapter.java
Helidon docs says that `Optional` is expensive and don't use it unless you need to. In the generator, optionals are more of an implementation detail and null or the default value is returned. For better performance, this PR replaces optionals with contains / get as Helidon suggests.
> Optimize helidon optionals - io.helidon.common.mapper.OptionalValue

- README.md
- http-generator-helidon/src/main/java/io/avaje/http/generator/helidon/nima/ControllerMethodWriter.java
- http-generator-helidon/src/main/java/io/avaje/http/generator/helidon/nima/ControllerWriter.java
- http-generator-helidon/src/main/java/io/avaje/http/generator/helidon/nima/NimaPlatformAdapter.java
- tests/test-nima/pom.xml
- tests/test-nima/src/main/java/org/example/AppRoles.java
- tests/test-nima/src/main/java/org/example/HelloController.java
- tests/test-nima/src/main/java/org/example/Roles.java
Helidon has security providers e.g. OIDC. These integrate with WebServer Security as `SecurityHandler`s with the shorthand `SecurityFeature.rolesAllowed(<roles>)` and the authorization provider will then validate the role before delegating to the actual handler.
This PR takes Avaje's `@Roles` and populates them and the rest is up to Helidon.
> Add roles support for Helidon

- http-client/pom.xml
- http-client/src/main/java/io/avaje/http/client/DHttpClientContext.java
- http-client/src/main/java/io/avaje/http/client/HttpClient.java
- http-generator-client/src/main/java/io/avaje/http/generator/client/ClientWriter.java
Since JDK 21, `java.net.HttpClient` now extends `AutoCloseable`, should we not follow suit?
- `io.avaje.http.client.HttpClient` now extends `AutoCloseable` (has no effect unless on 21 or higher)
- generated Client interface implementations will now additionally implement AutoClosable as well
> [http-client] Make clients `AutoCloseable`

- http-generator-jex/src/main/java/io/avaje/http/generator/jex/ControllerMethodWriter.java
- http-generator-jex/src/main/java/io/avaje/http/generator/jex/ControllerWriter.java
- http-generator-jex/src/main/java/io/avaje/http/generator/jex/JexAdapter.java
This will make it easier to support an HTMX extension for jex
> [Jex] Modify generated code for Jex controllers to use handler methods

- http-generator-jex/src/main/java/io/avaje/http/generator/jex/ControllerMethodWriter.java
Example:
```
var result = controller.someMethod(args);
if (result != null) {
ctx.json(result);
}
```
> [Jex generation] Add check for non null result in generated code

- http-generator-jex/src/main/java/io/avaje/http/generator/jex/ControllerMethodWriter.java
- tests/pom.xml
- tests/test-jex/src/main/java/org/example/Main.java
- tests/test-jex/src/main/java/org/example/web/TestController.java
Error controllers don't have paths
> [jex-generator] Fix jex error controller generation

- http-generator-jex/src/main/java/io/avaje/http/generator/jex/ControllerMethodWriter.java
- http-generator-jex/src/main/java/io/avaje/http/generator/jex/ControllerWriter.java
- http-generator-jex/src/main/java/io/avaje/http/generator/jex/JexProcessor.java
- pom.xml
- tests/pom.xml
- tests/test-client-generation/pom.xml
- tests/test-client-generation/src/main/resources/logback.xml
- tests/test-jex/src/main/java/org/example/web/HelloDto.java
- tests/test-jex/src/main/java/org/example/web/myapp/WebController.java
- tests/test-jex/src/main/java/org/example/web/myapp/WebHelloDto.java
- tests/test-jex/src/main/java/org/example/web/myapp/service/MyService.java
- tests/test-jex/src/main/resources/public/openapi.json
Adds the explicit Jsonb type generator we have for helidon/javalin to the jex generator
> [Jex-Generator] Jsonb Type generation

- http-client/src/main/java/io/avaje/http/client/DHttpClientBuilder.java
When on JDK 21+, the builder will default to the `VirtualThreadPerTask` Executor for the underlying `HttpClient`.
> [Http-Client] Use virtual thread executor by default

- http-client/pom.xml
- http-client/src/main/java/io/avaje/http/client/DSingleAdapter.java
- http-client/src/main/java/io/avaje/http/client/SingleBodyAdapter.java
- http-client/src/test/java/io/avaje/http/client/BaseWebTest.java
- http-client/src/test/java/io/avaje/http/client/HelloControllerTest.java
- http-client/src/test/java/io/avaje/http/client/HelloDtoAdapter.java
- http-client/src/test/java/org/example/github/RepoJsonAdapter.java
This provides a way to minimise the dependencies of an HttpClient that only has a single body type to support.
That is, make it easier to use sayjust avaje-json-core or avaje-json-node as a dependency to handle the response body &/or request body where the http endpoint only has the single body type to support [and arguably avaje-jsonb or Jackson is a bit "overkill"].
An alternative is this is to just to use raw body content like String or byte[], and handle it all without a BodyAdapter but this provides a more explicit API for that use case..
> [http-client] Add SingleBodyAdapter for client API with only a single body type

- http-client/src/main/java/io/avaje/http/client/BasicAuthIntercept.java
- http-client/src/test/java/io/avaje/http/client/BasicAuthInterceptTest.java
Provided as a helper method for code that wants the header value to then apply it explicitly [typically as a http Authorization header] rather than using this as a request intercept.
> [http-client] Add BasicAuthIntercept.header() helper method

- aws-cognito/http-client-authtoken/pom.xml
- aws-cognito/http-client-authtoken/src/main/java/io/avaje/aws/client/cognito/AmzCognitoAuthTokenProvider.java
- aws-cognito/http-client-authtoken/src/main/java/io/avaje/aws/client/cognito/CognitoAuthTokenProvider.java
- aws-cognito/http-client-authtoken/src/main/java/module-info.java
- aws-cognito/http-client-authtoken/src/test/java/io/avaje/aws/client/cognito/CognitoAuthTokenProviderTest.java
- aws-cognito/pom.xml
- pom.xml
An HttpClient AuthTokenProvider for AWS Cognito
> Add AWS CognitoAuthTokenProvider module

- http-generator-core/src/main/java/io/avaje/http/generator/core/Append.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/JsonBUtil.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/UType.java
- http-generator-core/src/test/java/io/avaje/http/generator/core/JsonBUtilTest.java
- tests/test-javalin-jsonb/src/main/java/org/example/myapp/web/test/GenericController.java
- add a method to UType to retrieve the parameters
- add debug toString to appender
Resolves #542
> Fix JsonB generic generation errors

- http-client/src/main/java/io/avaje/http/client/BearerTokenIntercept.java
- http-client/src/test/java/io/avaje/http/client/BearerTokenInterceptTest.java
Currently, the documentation provides instructions on how to build a bearer token provider, which assumes that tokens are short-lived and must be refreshed after some time. However, some REST APIs offer a bearer token authentication mechanism that relies on the API key/secret instead of short-lived tokens. Since this is a somewhat common use case, and given that we also have an existing implementation for basic auth, I feel like it makes sense to have this implementation offered out of the box too.
Examples:
- [Loops.so](https://loops.so/docs/api-reference/intro#authentication-steps)
- [OpenAI](https://platform.openai.com/docs/quickstart?language-preference=curl#make-your-first-api-request)
- [Notion](https://developers.notion.com/reference/authentication)
> Add Bearer authentication intercept

- http-client/src/test/java/io/avaje/http/client/DHttpClientRequestTest.java
- http-generator-client/src/main/java/io/avaje/http/generator/client/ClientWriter.java
Is there a need for them to be in a separate package?
also make them final.
> [client] Write clients to the same package

- http-generator-client/src/main/java/io/avaje/http/generator/client/ComponentMetaData.java
- tests/test-client-generation/src/main/java/org/example/JunkApi.java
Don't always put GeneratedHttpComponent into .httpclient as the client interface might NOT be public now with 546
> [client] Followup #546 - put GeneratedHttpComponent into top package

- http-api/src/main/java/io/avaje/http/api/PathTypeConversion.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/ElementReader.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/TypeMap.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/UType.java
- tests/test-jex/src/main/java/org/example/web/myapp/WebController.java
I wanted to contribute and asked @SentryMan for a good starter feature. I tried to emulate the style.
> added support for Optional Request Parameters

- http-api/src/main/java/io/avaje/http/api/PathTypeConversion.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/TypeMap.java
- http-generator-core/src/test/java/io/avaje/http/generator/core/TypeMapTest.java
- tests/test-jex/src/main/java/org/example/web/myapp/WebController.java
- tests/test-jex/src/test/java/org/example/web/HelloControllerTest.java
- Adds tests that were missing in HelloControllerTest that actually exercises the feature
- Fixes the controller URLs removing incorrect {myOptional} from urls
- Fixes PathTypeConversion to handle null values
- Adds missing javadoc on new public methods of PathTypeConversion
- Adds some useful unit tests for TypeMap.OptionalHandler
> Fix PR #550 Optional type wrapping of query parameters

- http-api/src/main/java/io/avaje/http/api/Client.java
- http-generator-client/src/main/java/io/avaje/http/generator/client/ClientProcessor.java
- tests/test-client-generation/src/main/java/org/example/package-info.java
- tests/test-client-generation/src/test/java/org/example/CommonApiTest.java
Now can do `@Client.Import(CustomType.class)`
--------
This is a breaking change
From:
```java
@Client.Import(types = OtherApi.class)
```
To:
```java
@Client.Import(value = OtherApi.class)
```
... and because it is value it can be now written as:
```java
@Client.Import(OtherApi.class)
```
> [client] Breaking change - Rename @Client.Import(types=...) to @Client.Import(value=...).  That is, rename types -> value

- http-generator-client/src/main/java/io/avaje/http/generator/client/ComponentReader.java
- tests/test-client/src/test/java/example/github/Dummy.java
It seems that generating a client during src/test compilation causes clients generated in src/main to be undetected during tests.
This PR makes it so that the main src/main/META-INF/services are also detected during test compilation
> [client] Fix test generation overriding main components

- aws-cognito/http-client-authtoken/pom.xml
- aws-cognito/http-client-authtoken/src/main/java/io/avaje/aws/client/cognito/AmzCognitoAuthTokenProvider.java
- http-client/pom.xml
- http-client/src/main/java/io/avaje/http/client/DSingleAdapter.java
- http-client/src/main/java/io/avaje/http/client/SingleBodyAdapter.java
- http-client/src/test/java/io/avaje/http/client/HelloControllerTest.java
For http-client SingleBodyAdapter and Cognito AuthTokenProvider
> Update to avaje-jsonb 3.0-RC7 with SimpleMapper renamed to JsonMapper

- http-generator-jex/src/main/java/io/avaje/http/generator/jex/ControllerWriter.java
- http-generator-jex/src/main/java/io/avaje/http/generator/jex/JexAdapter.java
- tests/pom.xml
- tests/test-jex/src/main/java/org/example/web/HelloController.java
- tests/test-jex/src/main/java/org/example/web/TestController.java
- tests/test-jex/src/main/java/org/example/web/myapp/WebController.java
If https://github.com/avaje/avaje-jex/pull/182 get's merged, this is required to properly generate jex handlers
> Update jex context package

- http-generator-core/src/main/java/io/avaje/http/generator/core/JsonBUtil.java
- http-generator-helidon/src/main/java/io/avaje/http/generator/helidon/nima/ControllerWriter.java
- http-generator-javalin/src/main/java/io/avaje/http/generator/javalin/ControllerWriter.java
- http-generator-jex/src/main/java/io/avaje/http/generator/jex/ControllerWriter.java
Now will not generate Jsonb imports/constructor if no json types are detected on the controller
> [generators] Remove jsonb generation if no jsontypes available

- http-generator-sigma/src/main/java/io/avaje/http/generator/sigma/ControllerMethodWriter.java
- tests/test-sigma/pom.xml
- tests/test-sigma/src/main/java/org/example/myapp/web/jstache/JstacheController.java
- tests/test-sigma/src/test/java/io/avaje/http/generator/SigmaProcessorTest.java
> [sigma-generator] add jstachio support

- http-generator-core/src/main/java/io/avaje/http/generator/core/ControllerReader.java
- http-generator-jex/src/main/java/io/avaje/http/generator/jex/JexAdapter.java
uses the body methods of jex. (Direct reading jsonb has the disadvantage of throwing an exception when the stream has been read)
> [jex-generator] use body stream methods

- http-generator-core/src/main/java/io/avaje/http/generator/core/MethodReader.java
- tests/test-javalin-jsonb/src/main/java/org/example/myapp/web/test/TestController2.java
- tests/test-nima-jsonb/src/main/java/org/example/TestController.java
> Add compiler error for GET json bodies

- .gitignore
- http-generator-core/src/main/java/io/avaje/http/generator/core/AnnotationCopier.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/BaseProcessor.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/PrimitiveUtil.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/TestClientWriter.java
- pom.xml
- tests/test-jex/pom.xml
- tests/test-jex/src/test/java/org/example/web/HelloControllerTest.java
- tests/test-nima/pom.xml
mostly resolves #584 with a few caveats
- won't generate client methods for controllers with a Context parameter
- won't generate for controllers that use API
There are some bugs to work out using this approach. It seems that during test compilation it causes the classes to get recompiled so inject complains with errors like  `No dependency provided for org.example.web.myapp.WebController on org.example.web.myapp.WebController$Route`
> Generate Test Clients during test compilation 

- http-generator-core/src/main/java/io/avaje/http/generator/core/openapi/MethodParamDocBuilder.java
- http-generator-helidon/src/main/java/io/avaje/http/generator/helidon/nima/ControllerWriter.java
- tests/test-javalin-jsonb/src/main/java/org/example/myapp/web/test/OpenAPIController.java
- tests/test-javalin-jsonb/src/test/resources/expectedOpenApi.json
- tests/test-nima-jsonb/pom.xml
- tests/test-nima-jsonb/src/main/java/org/example/OpenAPIController.java
- tests/test-nima-jsonb/src/test/java/io/avaje/http/generator/NimaProcessorTest.java
- tests/test-nima-jsonb/src/test/resources/expectedOpenApi.json
> Fix Helidon path openapi generation

- http-generator-core/src/main/java/io/avaje/http/generator/core/openapi/MethodParamDocBuilder.java
- tests/test-javalin-jsonb/src/main/resources/public/openapi.json
- tests/test-javalin-jsonb/src/test/resources/expectedOpenApi.json
- tests/test-javalin/src/main/resources/public/openapi.json
- tests/test-jex/src/main/resources/public/openapi.json
- tests/test-nima-jsonb/src/test/resources/expectedOpenApi.json
- tests/test-sigma/src/main/resources/public/openapi.json
```java
@QueryParam String lastName               // -> "lastName" (no bug here, this was OK)
@QueryParam("q-2") String param2          // -> "q-2"
@Header String contentLength              // -> "Content-Length" (because headers automatic names are Init-Camel)
@Header("x-oh") String otherHeader        // -> "x-on"
```
> Fix generated openapi.json parameter names

- http-generator-helidon/src/main/java/io/avaje/http/generator/helidon/nima/NimaPlatformAdapter.java
- tests/test-nima/pom.xml
- tests/test-nima/src/main/java/org/example/HelloController.java
- tests/test-nima/src/test/java/org/example/BaseWebTest.java
- tests/test-nima/src/test/java/org/example/HelloControllerTest.java
One or multiple params passes. Adding a test for NO parameters will fail.
> [helidon] Bug fix for list of query parameters or form parameters when parameters is empty

- http-generator-client/src/main/java/io/avaje/http/generator/client/ClientMethodWriter.java
- http-generator-client/src/test/java/io/avaje/http/generator/client/clients/ApiClient.java
- http-generator-client/src/test/java/io/avaje/http/generator/client/clients/PrivateClient2.java
Now will generate clients like this
```java
@Client
public interface ApiClient {
@Get("/consecutive/paths/generate")
String consecutive();
}
```
```java
@Override
public String consecutive(String accept) {
.path("consecutive/paths/generate")
.GET()
.asPlainString().body();
}
```
> [http-client] combine generated consecutive path literals

- http-client/src/main/java/io/avaje/http/client/DHttpClientRequest.java
Fixes error where `asyncBean(Type)` didn't not return an `java.net.http.HttpResponse` instance
> [Client] Fix async generic responses

- aws-cognito/http-client-authtoken/pom.xml
- http-client/pom.xml
- http-generator-core/src/main/java/io/avaje/http/generator/core/JsonBUtil.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/openapi/MediaType.java
- http-generator-helidon/src/main/java/io/avaje/http/generator/helidon/nima/ControllerMethodWriter.java
- http-generator-jex/src/main/java/io/avaje/http/generator/jex/ControllerMethodWriter.java
- http-generator-jex/src/main/java/io/avaje/http/generator/jex/JexAdapter.java
- tests/test-javalin-jsonb/pom.xml
- tests/test-jex/pom.xml
- tests/test-jex/src/main/java/org/example/web/HelloController.java
- tests/test-jex/src/main/java/org/example/web/HelloDto.java
- tests/test-jex/src/main/java/org/example/web/myapp/BarController.java
- tests/test-jex/src/main/java/org/example/web/myapp/BarInterface.java
- tests/test-jex/src/main/resources/public/openapi.json
- tests/test-jex/src/test/java/org/example/web/HelloControllerTest.java
- tests/test-nima-htmx/pom.xml
- tests/test-nima-jsonb/pom.xml
- tests/test-nima-jsonb/src/main/java/org/example/HelloController.java
- tests/test-nima-jsonb/src/test/java/org/example/HelloControllerTest.java
- tests/test-sigma/pom.xml
This is initially using JSON Array content rather than application/x-json-stream
> Add JsonB stream support

- http-client/src/main/java/io/avaje/http/client/DHttpClientRequest.java
- http-client/src/test/java/io/avaje/http/client/HelloControllerTest.java
- http-client/src/test/java/org/example/webserver/HelloController$Route.java
- http-client/src/test/java/org/example/webserver/HelloController.java
The HttpClient uses the BodyHandlers.ofLines() but was not filtering out empty lines. These empty lines can fail the assigned body handler (e.g. json parsing error).
The fix is to filter out empty lines when reading the stream.
> [client] Fix HttpClient support for reading empty stream

- http-client/src/main/java/io/avaje/http/client/DHttpClientBuilder.java
- http-client/src/test/java/org/example/dinject/ConfigureWithDITest.java
- http-generator-client/src/main/java/io/avaje/http/generator/client/ClientMethodWriter.java
- http-generator-client/src/test/java/io/avaje/http/generator/client/clients/ApiClient.java
- http-generator-core/src/main/java/io/avaje/http/generator/core/Util.java
It's truly annoying that I have to create multiple clients with different base URLs when I have a static endpoint.
> [client] Support Static URLs

- http-generator-core/src/main/java/io/avaje/http/generator/core/RequestScopeTypes.java
- tests/test-jex/src/main/java/org/example/web/myapp/ReqScopedController.java
It looks like Jex context was missing from the list
> Support Jex Request Scope controllers
