avaje/avaje-http

generator-core/src/main/java/io/dinject/webroutegen/openapi/MethodDocBuilder.java
I have added a regex which replaces the :parameter with {parameter} 
He takes everything after a : until a /
=> Fix path parameter

http-api/src/main/java/io/avaje/http/api/MediaType.java
Since byte arrays will be supported, let's add some common media types used with them;
=> Add more MediaTypes for byte[] responses;

.github/workflows/build.yml, .gitignore, http-generator-nima/pom.xml, http-generator-nima/src/main/java/io/avaje/http/generator/helidon/nima/ControllerMethodWriter.java
=> Fix Nima MediaType generation/Use JDK 19 For Nima Generator

http-generator-core/src/main/java/io/avaje/http/generator/core/MethodReader.java
=> Make Class level @Roles Inheritable.

http-api/README.md, http-hibernate-validator/pom.xml, http-hibernate-validator/src/main/java/io/avaje/http/hibernate/validator/BeanValidator.java
=> Jakarta Validator

http-generator-core/src/main/java/io/avaje/http/generator/core/Util.java, http-generator-core/src/main/java/io/avaje/http/generator/core/openapi/SchemaDocBuilder.java
Currently, the schemas get wonky when you have annotated parameters
=> Fix annotations on openapi schema

http-hibernate-validator/pom.xml, http-hibernate-validator/src/main/java/io/avaje/http/hibernate/validator/BeanValidator.java, http-hibernate-validator/src/main/java/io/avaje/http/hibernate/validator/ValidatorProvider.java
now doesn't need @InjectModules
=> AutoProvide Validator

http-api/pom.xml, http-client-gson-adapter/pom.xml, http-client/pom.xml, http-generator-client/pom.xml, http-generator-core/pom.xml, http-generator-core/src/main/java/io/avaje/http/generator/core/MethodReader.java, http-generator-helidon/pom.xml, http-generator-javalin/pom.xml, http-generator-jex/pom.xml, http-generator-nima/pom.xml, pom.xml
Currently getting OperationUnsupportedException
--------
Edit by Rob
This change is such that the roles for a given method are the roles defined on the method _**PLUS** the roles defined on the controller class / type_.
=> Fix such that Class Roles are added to Method Roles

tests/pom.xml, tests/test-client-generation/pom.xml, tests/test-client/pom.xml, tests/test-helidon/pom.xml, tests/test-javalin-jsonb/pom.xml, tests/test-javalin/pom.xml, tests/test-jex/pom.xml, tests/test-nima-jsonb/pom.xml, tests/test-nima/pom.xml
Doesn't it get tedious modifying every test pom for every version?
=> http version in test parent pom

http-api/src/main/java/io/avaje/http/api/PathTypeConversion.java, http-generator-core/src/main/java/io/avaje/http/generator/core/TypeMap.java
Now wraps invalid enum exception with the Path argument exception
=> Catch Enum Illegal State Exception

http-generator-client/src/main/java/io/avaje/http/generator/client/ClientMethodWriter.java, http-generator-client/src/main/java/io/avaje/http/generator/client/ClientProcessor.java, http-generator-client/src/main/java/io/avaje/http/generator/client/ClientWriter.java, http-generator-core/pom.xml, http-generator-core/src/main/java/io/avaje/http/generator/core/BaseControllerWriter.java, http-generator-core/src/main/java/io/avaje/http/generator/core/BaseProcessor.java, http-generator-core/src/main/java/io/avaje/http/generator/core/BeanParamReader.java, http-generator-core/src/main/java/io/avaje/http/generator/core/ControllerReader.java, http-generator-core/src/main/java/io/avaje/http/generator/core/ElementReader.java, http-generator-core/src/main/java/io/avaje/http/generator/core/MethodParam.java, http-generator-core/src/main/java/io/avaje/http/generator/core/MethodReader.java, http-generator-core/src/main/java/io/avaje/http/generator/core/ProcessingContext.java, http-generator-helidon/src/main/java/io/avaje/http/generator/helidon/ControllerMethodWriter.java, http-generator-helidon/src/main/java/io/avaje/http/generator/helidon/ControllerWriter.java, http-generator-helidon/src/main/java/io/avaje/http/generator/helidon/HelidonProcessor.java, http-generator-javalin/src/main/java/io/avaje/http/generator/javalin/ControllerMethodWriter.java, http-generator-javalin/src/main/java/io/avaje/http/generator/javalin/ControllerWriter.java, http-generator-javalin/src/main/java/io/avaje/http/generator/javalin/JavalinProcessor.java, http-generator-jex/src/main/java/io/avaje/http/generator/jex/ControllerMethodWriter.java, http-generator-jex/src/main/java/io/avaje/http/generator/jex/ControllerWriter.java, http-generator-jex/src/main/java/io/avaje/http/generator/jex/JexProcessor.java, http-generator-nima/src/main/java/io/avaje/http/generator/helidon/nima/ControllerMethodWriter.java, http-generator-nima/src/main/java/io/avaje/http/generator/helidon/nima/ControllerWriter.java, http-generator-nima/src/main/java/io/avaje/http/generator/helidon/nima/NimaProcessor.java, tests/test-nima-jsonb/.factorypath
=> Static Processor Context

http-generator-core/src/main/java/io/avaje/http/generator/core/ProcessingContext.java
You already knew this was coming
=> Single ThreadLocal Context

http-generator-client/src/main/java/module-info.java, http-generator-helidon/src/main/java/module-info.java, http-generator-javalin/src/main/java/module-info.java, http-generator-jex/src/main/java/module-info.java, http-generator-nima/src/main/java/module-info.java
=> Fix #188 - IllegalAccessError io.avaje.http.generator.core.openapi.KnownTypes ... does not read module java.sql

http-generator-javalin/src/main/java/io/avaje/http/generator/javalin/JavalinAdapter.java
=> Use Context#bodyStreamAsClass(...)

http-client/src/main/java/io/avaje/http/client/DHttpClientBuilder.java, http-client/src/main/java/io/avaje/http/client/DHttpClientContextBuilder.java, http-client/src/main/java/io/avaje/http/client/HttpClient.java, http-client/src/main/java/io/avaje/http/client/HttpClientContext.java
Now can add multiple interceptors at once.
=> [http client] Support VarArg interceptors for HttpClient

http-generator-core/src/main/java/io/avaje/http/generator/core/TypeMap.java, tests/test-javalin-jsonb/src/main/java/org/example/myapp/web/test/TestController2.java
=> Fix Enum Path Parsing

README.md
Inject isn't actually needed there
=> Remove inject from quickstart

http-generator-core/src/main/java/io/avaje/http/generator/core/ProcessingContext.java, http-generator-nima/src/main/java/io/avaje/http/generator/helidon/nima/ControllerMethodWriter.java, tests/test-nima-jsonb/src/main/java/org/example/TestController.java
- use `transferTo` to write input stream contents to the nima output stream
- can use custom Media Types
- can handle checked exceptions thrown by controllers
=> (nima-generator) Support `InputStream` Return Types

tests/pom.xml, tests/test-nima-jsonb/pom.xml, tests/test-nima-jsonb/src/main/java/org/example/Main.java, tests/test-nima/pom.xml, tests/test-nima/src/main/java/org/example/Main.java
Nima had a new release, so updated the tests.
=> Nima M1 Tests

http-api/src/main/java/io/avaje/http/api/ValidationException.java, http-generator-core/src/main/java/io/avaje/http/generator/core/ElementReader.java, http-generator-helidon/src/main/java/io/avaje/http/generator/helidon/nima/ControllerMethodWriter.java, http-generator-helidon/src/main/java/io/avaje/http/generator/helidon/nima/ControllerWriter.java, http-generator-helidon/src/main/java/io/avaje/http/generator/helidon/nima/NimaPlatformAdapter.java, http-generator-javalin/src/main/java/io/avaje/http/generator/javalin/ControllerMethodWriter.java, http-generator-jex/src/main/java/io/avaje/http/generator/jex/ControllerMethodWriter.java
Plus use platform indent with validLanguage and validator() generated code
=> Nima - have validation Accept-Language helper method

http-api/src/main/java/io/avaje/http/api/BeanParam.java, http-api/src/main/java/io/avaje/http/api/DefaultException.java, http-api/src/main/java/io/avaje/http/api/ExceptionHandler.java, http-generator-core/src/main/java/io/avaje/http/generator/core/JsonBUtil.java, http-generator-core/src/main/java/io/avaje/http/generator/core/MethodReader.java, http-generator-core/src/main/java/io/avaje/http/generator/core/WebMethod.java, http-generator-core/src/main/java/io/avaje/http/generator/core/package-info.java, http-generator-helidon/src/main/java/io/avaje/http/generator/helidon/nima/ControllerMethodWriter.java, http-generator-javalin/src/main/java/io/avaje/http/generator/javalin/ControllerMethodWriter.java, tests/test-javalin-jsonb/src/main/java/org/example/myapp/web/test/TestController2.java, tests/test-nima-jsonb/pom.xml, tests/test-nima-jsonb/src/main/java/org/example/TestController.java
Adds a new exception handler annotation for generating error handler adapters.
- Adds new annotation
- Modify Javalin/Helidon generation to read the annotation and generate classes
relies on #252
=> Add `@ExceptionHandler`

README.md, http-generator-client/src/test/java/io/avaje/http/generator/client/ClientProcessorTest.java, http-generator-client/src/test/java/io/avaje/http/generator/client/clients/Body.java, http-generator-client/src/test/java/io/avaje/http/generator/client/clients/UserClient.java, http-generator-core/src/main/java/io/avaje/http/generator/core/ControllerReader.java, http-generator-core/src/main/java/io/avaje/http/generator/core/ElementReader.java, http-generator-core/src/main/java/io/avaje/http/generator/core/MethodParam.java
It seems array brackets were being generated when using client generator with varargs.
=> Sanitize Generated Imports

http-api/src/main/java/io/avaje/http/api/ExceptionHandler.java, http-generator-core/src/main/java/io/avaje/http/generator/core/MethodReader.java, http-generator-core/src/main/java/io/avaje/http/generator/core/openapi/MethodDocBuilder.java, http-generator-helidon/src/main/java/io/avaje/http/generator/helidon/nima/ControllerMethodWriter.java, http-generator-javalin/src/main/java/io/avaje/http/generator/javalin/ControllerMethodWriter.java, http-generator-jex/src/main/java/io/avaje/http/generator/jex/ControllerMethodWriter.java, tests/test-nima-jsonb/src/main/java/org/example/ErrorController.java, tests/test-nima-jsonb/src/main/java/org/example/HelloController.java, tests/test-nima-jsonb/src/main/java/org/example/TestController.java, tests/test-nima-jsonb/src/test/java/org/example/TestControllerTest.java, tests/test-nima-jsonb/src/test/java/org/example/TestPair.java
To specifying the status code when the ExceptionHandler returns an object that is sent to the response
=> Add statusCode attribute to ExceptionHandler

http-client/pom.xml, http-client/src/main/java/io/avaje/http/client/BasicAuthIntercept.java, http-client/src/main/java/io/avaje/http/client/DBaseBuilder.java, http-client/src/main/java/io/avaje/http/client/DHttpApi.java, http-client/src/main/java/io/avaje/http/client/DHttpClientContext.java, http-client/src/main/java/io/avaje/http/client/DHttpClientRequest.java, http-client/src/main/java/io/avaje/http/client/GzipUtil.java, http-client/src/main/java/io/avaje/http/client/JacksonBodyAdapter.java, http-client/src/test/java/io/avaje/http/client/DHttpClientContextTest.java, http-client/src/test/java/org/example/github/GithubTest.java, tests/test-client/src/main/java/example/github/httpclient/GeneratedHttpComponent.java, tests/test-client/src/main/java/module-info.java
also, code generation or bust.
=> [http-client] Remove reflective creation of client interface implementation (must be service loaded now)

http-generator-client/src/main/java/io/avaje/http/generator/client/ClientProcessor.java, http-generator-core/src/main/java/io/avaje/http/generator/core/ProcessingContext.java, http-generator-helidon/pom.xml, http-generator-helidon/src/main/java/io/avaje/http/generator/helidon/nima/NimaProcessor.java, http-generator-helidon/src/main/java/module-info.java, http-generator-helidon/src/main/resources/META-INF/services/javax.annotation.processing.Processor, pom.xml
Fail compilation on modular projects if people forget to add the required `provides` clause.
=> [http-client] Validate Module

http-generator-helidon/src/main/java/io/avaje/http/generator/helidon/nima/ControllerWriter.java, tests/pom.xml
it seems we're in the final stretch
=> Helidon-RC1

.github/workflows/dependabot-merge.yml, http-generator-client/src/main/java/io/avaje/http/generator/client/AnnotationUtil.java
Branch protections should be enabled
=> Enable Dependabot Auto-Merge

tests/pom.xml, tests/test-javalin-jsonb/pom.xml, tests/test-javalin/pom.xml
By the way, can we get an RC candidate for those lads who want to use this beta version with avaje?
=> Test Javalin 6 `beta.2`

http-api/src/main/java/io/avaje/http/api/PathTypeConversion.java, http-api/src/test/java/io/avaje/http/api/PathTypeConversionTest.java, http-generator-core/src/main/java/io/avaje/http/generator/core/TypeMap.java
Also support enums that are not all upper case (if people choose to do that).
=> Fix #354 - Add toEnum() to PathTypeConversion, also support non-upper case

http-generator-core/src/main/java/io/avaje/http/generator/core/MethodReader.java, http-generator-core/src/main/java/io/avaje/http/generator/core/UType.java
now will not exclude java lang sub packages
=> Fix Java Lang imports

http-client/README.md
The loom stuff is cool, but not exactly up to date since it was done on JDK 17
=> [http-client] Update README.md

README.md
=> Update `proc` note

http-generator-core/src/main/java/io/avaje/http/generator/core/ProcessingContext.java, pom.xml
=> Use prisms to validate modules

http-generator-jex/src/main/java/io/avaje/http/generator/jex/ControllerMethodWriter.java, http-generator-jex/src/main/java/io/avaje/http/generator/jex/ControllerWriter.java, tests/test-jex/pom.xml, tests/test-jex/src/main/java/org/example/web/ContentController.java, tests/test-jex/src/main/java/org/example/web/MyTemplateRender.java, tests/test-jex/src/main/java/org/example/web/template/ViewHome.java, tests/test-jex/src/main/java/org/example/web/template/package-info.java, tests/test-jex/src/main/resources/public/openapi.json, tests/test-jex/src/main/resources/ui/fragments/layout.mustache, tests/test-jex/src/main/resources/ui/home.mustache, tests/test-jex/src/main/resources/ui/name.mustache
Currently, it does not handle the case of common routing entry (for normal processing and hx).
=> [Jex generation] Add initial support for htmx

http-generator-jex/src/main/java/io/avaje/http/generator/jex/ControllerMethodWriter.java, tests/pom.xml, tests/test-jex/src/main/resources/public/openapi.json
=> [Jex Generator] Use optimized Jex jsonb method

tests/test-javalin-jsonb/src/main/java/org/example/myapp/web/test/OpenAPIController.java, tests/test-javalin-jsonb/src/main/resources/public/openapi.json, tests/test-javalin-jsonb/src/test/java/io/avaje/http/generator/JavalinProcessorTest.java, tests/test-javalin-jsonb/src/test/resources/expectedOpenApi.json
Followup PR to come related to incorrect generated openapi.json
=> No effective change - add more parameters to test openapi.json

http-api/src/main/java/io/avaje/http/api/SupressLogging.java, http-generator-client/src/main/java/io/avaje/http/generator/client/ClientMethodWriter.java, http-generator-client/src/test/java/io/avaje/http/generator/client/clients/TitanFall.java, tests/test-client/src/main/java/example/github/Simple.java
=> [client] Add SuppressLogging Annotation
